### ISSUE TITLE
Update Webhooks sample

### ISSUE THREAD

**Issue by repat** [HubSpot/sample-apps-webhooks#11]
This code uses the deprecated Webhooks class:
https://github.com/HubSpot/sample-apps-webhooks/blob/main/php/src/actions/webhooks/handle.php

The latest class, which also supports version 3 of the signature is found in the `Signature` class:
https://github.com/HubSpot/hubspot-api-php/blob/master/lib/Utils/Signature.php

**Comment by ksvirkou-hubspot** [comment]
Hi @repat .
Thank you for reporting it.
We've updated Webhooks sample.
